version: "3.10"

services:
  core:
    runtime: nvidia
    container_name: huggingface-exp
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:11.8.0-devel-ubuntu20.04
        - PYTHON_VERSION=3.10
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
        - 8002:8002